-- Generated by scripts/generate-seed-sql.ts — do not edit by hand.
-- Source of truth: src/data/seedExcerpts.ts

insert into excerpts (slug, composer, work, movement, section_label, instrument, difficulty, typical_prep_weeks, reference_tempo_range, aliases)
values ('berlioz-symphonie-fantastique-un-bal-harp1', 'Berlioz', 'Symphonie fantastique', 'II. Un bal', 'Harp 1: both cadenzas + waltz', 'harp', 5, 8, '[56,63]'::int4range, array['Symphonie fantastique', 'Berlioz Sym Fantastique mvt 2', 'Un bal', 'Berlioz waltz', 'Symph fantastique harp 1'])
on conflict (slug) do update set
  composer = excluded.composer, work = excluded.work, movement = excluded.movement,
  section_label = excluded.section_label, difficulty = excluded.difficulty,
  typical_prep_weeks = excluded.typical_prep_weeks,
  reference_tempo_range = excluded.reference_tempo_range, aliases = excluded.aliases;

insert into excerpts (slug, composer, work, movement, section_label, instrument, difficulty, typical_prep_weeks, reference_tempo_range, aliases)
values ('berlioz-symphonie-fantastique-un-bal-harp2', 'Berlioz', 'Symphonie fantastique', 'II. Un bal', 'Harp 2 part', 'harp', 4, 5, '[56,63]'::int4range, array['Symphonie fantastique harp 2', 'Un bal second harp'])
on conflict (slug) do update set
  composer = excluded.composer, work = excluded.work, movement = excluded.movement,
  section_label = excluded.section_label, difficulty = excluded.difficulty,
  typical_prep_weeks = excluded.typical_prep_weeks,
  reference_tempo_range = excluded.reference_tempo_range, aliases = excluded.aliases;

insert into excerpts (slug, composer, work, movement, section_label, instrument, difficulty, typical_prep_weeks, reference_tempo_range, aliases)
values ('tchaikovsky-nutcracker-waltz-of-the-flowers-cadenza', 'Tchaikovsky', 'The Nutcracker', 'Waltz of the Flowers', 'Cadenza', 'harp', 5, 8, '[66,76]'::int4range, array['Nutcracker cadenza', 'Waltz of the Flowers', 'Tchaik Nutcracker', 'Flower waltz cadenza'])
on conflict (slug) do update set
  composer = excluded.composer, work = excluded.work, movement = excluded.movement,
  section_label = excluded.section_label, difficulty = excluded.difficulty,
  typical_prep_weeks = excluded.typical_prep_weeks,
  reference_tempo_range = excluded.reference_tempo_range, aliases = excluded.aliases;

insert into excerpts (slug, composer, work, movement, section_label, instrument, difficulty, typical_prep_weeks, reference_tempo_range, aliases)
values ('tchaikovsky-swan-lake-act2-cadenza', 'Tchaikovsky', 'Swan Lake', 'Act II', 'Pas de deux cadenzas', 'harp', 4, 6, null, array['Swan Lake cadenza', 'White Swan pas de deux', 'Tchaik Swan Lake'])
on conflict (slug) do update set
  composer = excluded.composer, work = excluded.work, movement = excluded.movement,
  section_label = excluded.section_label, difficulty = excluded.difficulty,
  typical_prep_weeks = excluded.typical_prep_weeks,
  reference_tempo_range = excluded.reference_tempo_range, aliases = excluded.aliases;

insert into excerpts (slug, composer, work, movement, section_label, instrument, difficulty, typical_prep_weeks, reference_tempo_range, aliases)
values ('tchaikovsky-sleeping-beauty-rose-adagio-cadenza', 'Tchaikovsky', 'The Sleeping Beauty', 'Act I', 'Rose Adagio cadenza', 'harp', 4, 5, null, array['Sleeping Beauty cadenza', 'Rose Adagio'])
on conflict (slug) do update set
  composer = excluded.composer, work = excluded.work, movement = excluded.movement,
  section_label = excluded.section_label, difficulty = excluded.difficulty,
  typical_prep_weeks = excluded.typical_prep_weeks,
  reference_tempo_range = excluded.reference_tempo_range, aliases = excluded.aliases;

insert into excerpts (slug, composer, work, movement, section_label, instrument, difficulty, typical_prep_weeks, reference_tempo_range, aliases)
values ('ravel-tzigane-cadenza', 'Ravel', 'Tzigane', null, 'Harp cadenza (luthéal section)', 'harp', 5, 8, null, array['Tzigane', 'Ravel Tzigane harp cadenza'])
on conflict (slug) do update set
  composer = excluded.composer, work = excluded.work, movement = excluded.movement,
  section_label = excluded.section_label, difficulty = excluded.difficulty,
  typical_prep_weeks = excluded.typical_prep_weeks,
  reference_tempo_range = excluded.reference_tempo_range, aliases = excluded.aliases;

insert into excerpts (slug, composer, work, movement, section_label, instrument, difficulty, typical_prep_weeks, reference_tempo_range, aliases)
values ('britten-young-persons-guide-variation', 'Britten', 'The Young Person''s Guide to the Orchestra', null, 'Variation J (harp variation)', 'harp', 4, 6, null, array['Young Person''s Guide', 'Britten YPG', 'Britten variation'])
on conflict (slug) do update set
  composer = excluded.composer, work = excluded.work, movement = excluded.movement,
  section_label = excluded.section_label, difficulty = excluded.difficulty,
  typical_prep_weeks = excluded.typical_prep_weeks,
  reference_tempo_range = excluded.reference_tempo_range, aliases = excluded.aliases;

insert into excerpts (slug, composer, work, movement, section_label, instrument, difficulty, typical_prep_weeks, reference_tempo_range, aliases)
values ('donizetti-lucia-harp-solo', 'Donizetti', 'Lucia di Lammermoor', 'Act I', 'Harp solo (Scene 2 prelude)', 'harp', 4, 6, null, array['Lucia harp solo', 'Lucia di Lammermoor solo', 'Donizetti solo'])
on conflict (slug) do update set
  composer = excluded.composer, work = excluded.work, movement = excluded.movement,
  section_label = excluded.section_label, difficulty = excluded.difficulty,
  typical_prep_weeks = excluded.typical_prep_weeks,
  reference_tempo_range = excluded.reference_tempo_range, aliases = excluded.aliases;

insert into excerpts (slug, composer, work, movement, section_label, instrument, difficulty, typical_prep_weeks, reference_tempo_range, aliases)
values ('smetana-vysehrad-opening', 'Smetana', 'Má vlast: Vyšehrad', null, 'Opening harp solos', 'harp', 3, 4, null, array['Vysehrad', 'Ma vlast opening', 'Smetana Moldau cycle opening'])
on conflict (slug) do update set
  composer = excluded.composer, work = excluded.work, movement = excluded.movement,
  section_label = excluded.section_label, difficulty = excluded.difficulty,
  typical_prep_weeks = excluded.typical_prep_weeks,
  reference_tempo_range = excluded.reference_tempo_range, aliases = excluded.aliases;

insert into excerpts (slug, composer, work, movement, section_label, instrument, difficulty, typical_prep_weeks, reference_tempo_range, aliases)
values ('rimsky-korsakov-capriccio-espagnol-cadenza', 'Rimsky-Korsakov', 'Capriccio espagnol', 'IV. Scena e canto gitano', 'Harp cadenza', 'harp', 4, 5, null, array['Capriccio espagnol', 'R-K Capriccio cadenza'])
on conflict (slug) do update set
  composer = excluded.composer, work = excluded.work, movement = excluded.movement,
  section_label = excluded.section_label, difficulty = excluded.difficulty,
  typical_prep_weeks = excluded.typical_prep_weeks,
  reference_tempo_range = excluded.reference_tempo_range, aliases = excluded.aliases;

insert into excerpts (slug, composer, work, movement, section_label, instrument, difficulty, typical_prep_weeks, reference_tempo_range, aliases)
values ('debussy-danses-sacree-et-profane', 'Debussy', 'Danses sacrée et profane', null, 'Complete (with strings)', 'harp', 5, 10, '[69,80]'::int4range, array['Danses', 'Debussy Danses', 'Danse sacree', 'Danse profane'])
on conflict (slug) do update set
  composer = excluded.composer, work = excluded.work, movement = excluded.movement,
  section_label = excluded.section_label, difficulty = excluded.difficulty,
  typical_prep_weeks = excluded.typical_prep_weeks,
  reference_tempo_range = excluded.reference_tempo_range, aliases = excluded.aliases;

insert into excerpts (slug, composer, work, movement, section_label, instrument, difficulty, typical_prep_weeks, reference_tempo_range, aliases)
values ('ravel-introduction-et-allegro', 'Ravel', 'Introduction et Allegro', null, 'Complete (solo with septet)', 'harp', 5, 12, null, array['Intro and Allegro', 'Ravel Introduction and Allegro', 'I&A'])
on conflict (slug) do update set
  composer = excluded.composer, work = excluded.work, movement = excluded.movement,
  section_label = excluded.section_label, difficulty = excluded.difficulty,
  typical_prep_weeks = excluded.typical_prep_weeks,
  reference_tempo_range = excluded.reference_tempo_range, aliases = excluded.aliases;

insert into excerpts (slug, composer, work, movement, section_label, instrument, difficulty, typical_prep_weeks, reference_tempo_range, aliases)
values ('mozart-concerto-flute-harp-k299-mvt1', 'Mozart', 'Concerto for Flute and Harp, K. 299', 'I. Allegro', null, 'harp', 4, 10, null, array['Mozart concerto', 'K299', 'Flute and harp concerto'])
on conflict (slug) do update set
  composer = excluded.composer, work = excluded.work, movement = excluded.movement,
  section_label = excluded.section_label, difficulty = excluded.difficulty,
  typical_prep_weeks = excluded.typical_prep_weeks,
  reference_tempo_range = excluded.reference_tempo_range, aliases = excluded.aliases;

insert into excerpts (slug, composer, work, movement, section_label, instrument, difficulty, typical_prep_weeks, reference_tempo_range, aliases)
values ('handel-concerto-bflat-mvt1', 'Handel', 'Concerto in B-flat major, Op. 4 No. 6', 'I. Andante allegro', null, 'harp', 3, 6, null, array['Handel concerto', 'Handel B-flat'])
on conflict (slug) do update set
  composer = excluded.composer, work = excluded.work, movement = excluded.movement,
  section_label = excluded.section_label, difficulty = excluded.difficulty,
  typical_prep_weeks = excluded.typical_prep_weeks,
  reference_tempo_range = excluded.reference_tempo_range, aliases = excluded.aliases;

insert into excerpts (slug, composer, work, movement, section_label, instrument, difficulty, typical_prep_weeks, reference_tempo_range, aliases)
values ('ginastera-harp-concerto-mvt1', 'Ginastera', 'Harp Concerto, Op. 25', 'I. Allegro giusto', null, 'harp', 5, 14, null, array['Ginastera', 'Ginastera concerto'])
on conflict (slug) do update set
  composer = excluded.composer, work = excluded.work, movement = excluded.movement,
  section_label = excluded.section_label, difficulty = excluded.difficulty,
  typical_prep_weeks = excluded.typical_prep_weeks,
  reference_tempo_range = excluded.reference_tempo_range, aliases = excluded.aliases;

insert into excerpts (slug, composer, work, movement, section_label, instrument, difficulty, typical_prep_weeks, reference_tempo_range, aliases)
values ('ravel-daphnis-suite2-lever-du-jour', 'Ravel', 'Daphnis et Chloé, Suite No. 2', 'Lever du jour', null, 'harp', 4, 5, null, array['Daphnis', 'Daphnis and Chloe', 'Lever du jour'])
on conflict (slug) do update set
  composer = excluded.composer, work = excluded.work, movement = excluded.movement,
  section_label = excluded.section_label, difficulty = excluded.difficulty,
  typical_prep_weeks = excluded.typical_prep_weeks,
  reference_tempo_range = excluded.reference_tempo_range, aliases = excluded.aliases;

insert into excerpts (slug, composer, work, movement, section_label, instrument, difficulty, typical_prep_weeks, reference_tempo_range, aliases)
values ('ravel-la-valse', 'Ravel', 'La valse', null, 'Harp 1: cadenza figures + glissandi', 'harp', 4, 5, null, array['La valse'])
on conflict (slug) do update set
  composer = excluded.composer, work = excluded.work, movement = excluded.movement,
  section_label = excluded.section_label, difficulty = excluded.difficulty,
  typical_prep_weeks = excluded.typical_prep_weeks,
  reference_tempo_range = excluded.reference_tempo_range, aliases = excluded.aliases;

insert into excerpts (slug, composer, work, movement, section_label, instrument, difficulty, typical_prep_weeks, reference_tempo_range, aliases)
values ('ravel-ma-mere-loye-jardin-feerique', 'Ravel', 'Ma mère l''Oye', 'V. Le jardin féerique', null, 'harp', 3, 3, null, array['Mother Goose', 'Jardin feerique'])
on conflict (slug) do update set
  composer = excluded.composer, work = excluded.work, movement = excluded.movement,
  section_label = excluded.section_label, difficulty = excluded.difficulty,
  typical_prep_weeks = excluded.typical_prep_weeks,
  reference_tempo_range = excluded.reference_tempo_range, aliases = excluded.aliases;

insert into excerpts (slug, composer, work, movement, section_label, instrument, difficulty, typical_prep_weeks, reference_tempo_range, aliases)
values ('ravel-alborada-del-gracioso', 'Ravel', 'Alborada del gracioso', null, null, 'harp', 4, 4, null, array['Alborada'])
on conflict (slug) do update set
  composer = excluded.composer, work = excluded.work, movement = excluded.movement,
  section_label = excluded.section_label, difficulty = excluded.difficulty,
  typical_prep_weeks = excluded.typical_prep_weeks,
  reference_tempo_range = excluded.reference_tempo_range, aliases = excluded.aliases;

insert into excerpts (slug, composer, work, movement, section_label, instrument, difficulty, typical_prep_weeks, reference_tempo_range, aliases)
values ('ravel-rapsodie-espagnole', 'Ravel', 'Rapsodie espagnole', 'I. Prélude à la nuit / IV. Feria', null, 'harp', 4, 4, null, array['Rapsodie espagnole'])
on conflict (slug) do update set
  composer = excluded.composer, work = excluded.work, movement = excluded.movement,
  section_label = excluded.section_label, difficulty = excluded.difficulty,
  typical_prep_weeks = excluded.typical_prep_weeks,
  reference_tempo_range = excluded.reference_tempo_range, aliases = excluded.aliases;

insert into excerpts (slug, composer, work, movement, section_label, instrument, difficulty, typical_prep_weeks, reference_tempo_range, aliases)
values ('debussy-la-mer', 'Debussy', 'La mer', null, 'Harp 1 exposed passages (mvts I & III)', 'harp', 4, 4, null, array['La mer'])
on conflict (slug) do update set
  composer = excluded.composer, work = excluded.work, movement = excluded.movement,
  section_label = excluded.section_label, difficulty = excluded.difficulty,
  typical_prep_weeks = excluded.typical_prep_weeks,
  reference_tempo_range = excluded.reference_tempo_range, aliases = excluded.aliases;

insert into excerpts (slug, composer, work, movement, section_label, instrument, difficulty, typical_prep_weeks, reference_tempo_range, aliases)
values ('debussy-prelude-apres-midi', 'Debussy', 'Prélude à l''après-midi d''un faune', null, 'Harp 1 part', 'harp', 3, 3, null, array['Afternoon of a Faun', 'Apres-midi', 'Faun'])
on conflict (slug) do update set
  composer = excluded.composer, work = excluded.work, movement = excluded.movement,
  section_label = excluded.section_label, difficulty = excluded.difficulty,
  typical_prep_weeks = excluded.typical_prep_weeks,
  reference_tempo_range = excluded.reference_tempo_range, aliases = excluded.aliases;

insert into excerpts (slug, composer, work, movement, section_label, instrument, difficulty, typical_prep_weeks, reference_tempo_range, aliases)
values ('debussy-nocturnes-fetes-sirenes', 'Debussy', 'Nocturnes', 'II. Fêtes', null, 'harp', 3, 3, null, array['Fetes', 'Debussy Nocturnes'])
on conflict (slug) do update set
  composer = excluded.composer, work = excluded.work, movement = excluded.movement,
  section_label = excluded.section_label, difficulty = excluded.difficulty,
  typical_prep_weeks = excluded.typical_prep_weeks,
  reference_tempo_range = excluded.reference_tempo_range, aliases = excluded.aliases;

insert into excerpts (slug, composer, work, movement, section_label, instrument, difficulty, typical_prep_weeks, reference_tempo_range, aliases)
values ('strauss-ein-heldenleben', 'R. Strauss', 'Ein Heldenleben', null, 'Harp 1: love scene + ending', 'harp', 4, 5, null, array['Heldenleben', 'Ein Heldenleben harp'])
on conflict (slug) do update set
  composer = excluded.composer, work = excluded.work, movement = excluded.movement,
  section_label = excluded.section_label, difficulty = excluded.difficulty,
  typical_prep_weeks = excluded.typical_prep_weeks,
  reference_tempo_range = excluded.reference_tempo_range, aliases = excluded.aliases;

insert into excerpts (slug, composer, work, movement, section_label, instrument, difficulty, typical_prep_weeks, reference_tempo_range, aliases)
values ('strauss-don-juan', 'R. Strauss', 'Don Juan', null, 'Exposed arpeggio passages', 'harp', 4, 4, null, array['Don Juan'])
on conflict (slug) do update set
  composer = excluded.composer, work = excluded.work, movement = excluded.movement,
  section_label = excluded.section_label, difficulty = excluded.difficulty,
  typical_prep_weeks = excluded.typical_prep_weeks,
  reference_tempo_range = excluded.reference_tempo_range, aliases = excluded.aliases;

insert into excerpts (slug, composer, work, movement, section_label, instrument, difficulty, typical_prep_weeks, reference_tempo_range, aliases)
values ('strauss-tod-und-verklaerung', 'R. Strauss', 'Tod und Verklärung', null, 'Transfiguration section', 'harp', 3, 3, null, array['Death and Transfiguration', 'Tod und Verklarung'])
on conflict (slug) do update set
  composer = excluded.composer, work = excluded.work, movement = excluded.movement,
  section_label = excluded.section_label, difficulty = excluded.difficulty,
  typical_prep_weeks = excluded.typical_prep_weeks,
  reference_tempo_range = excluded.reference_tempo_range, aliases = excluded.aliases;

insert into excerpts (slug, composer, work, movement, section_label, instrument, difficulty, typical_prep_weeks, reference_tempo_range, aliases)
values ('strauss-salome-dance', 'R. Strauss', 'Salome', 'Dance of the Seven Veils', null, 'harp', 4, 4, null, array['Salome', 'Seven Veils'])
on conflict (slug) do update set
  composer = excluded.composer, work = excluded.work, movement = excluded.movement,
  section_label = excluded.section_label, difficulty = excluded.difficulty,
  typical_prep_weeks = excluded.typical_prep_weeks,
  reference_tempo_range = excluded.reference_tempo_range, aliases = excluded.aliases;

insert into excerpts (slug, composer, work, movement, section_label, instrument, difficulty, typical_prep_weeks, reference_tempo_range, aliases)
values ('mahler-symphony5-adagietto', 'Mahler', 'Symphony No. 5', 'IV. Adagietto', null, 'harp', 3, 4, '[50,60]'::int4range, array['Mahler 5', 'Adagietto', 'Mahler Symphony No. 5 IV'])
on conflict (slug) do update set
  composer = excluded.composer, work = excluded.work, movement = excluded.movement,
  section_label = excluded.section_label, difficulty = excluded.difficulty,
  typical_prep_weeks = excluded.typical_prep_weeks,
  reference_tempo_range = excluded.reference_tempo_range, aliases = excluded.aliases;

insert into excerpts (slug, composer, work, movement, section_label, instrument, difficulty, typical_prep_weeks, reference_tempo_range, aliases)
values ('mahler-symphony1', 'Mahler', 'Symphony No. 1', null, 'Exposed passages (mvts I & IV)', 'harp', 3, 3, null, array['Mahler 1', 'Titan'])
on conflict (slug) do update set
  composer = excluded.composer, work = excluded.work, movement = excluded.movement,
  section_label = excluded.section_label, difficulty = excluded.difficulty,
  typical_prep_weeks = excluded.typical_prep_weeks,
  reference_tempo_range = excluded.reference_tempo_range, aliases = excluded.aliases;

insert into excerpts (slug, composer, work, movement, section_label, instrument, difficulty, typical_prep_weeks, reference_tempo_range, aliases)
values ('bruckner-symphony8-adagio', 'Bruckner', 'Symphony No. 8', 'III. Adagio', 'Harp arpeggios', 'harp', 3, 3, null, array['Bruckner 8'])
on conflict (slug) do update set
  composer = excluded.composer, work = excluded.work, movement = excluded.movement,
  section_label = excluded.section_label, difficulty = excluded.difficulty,
  typical_prep_weeks = excluded.typical_prep_weeks,
  reference_tempo_range = excluded.reference_tempo_range, aliases = excluded.aliases;

insert into excerpts (slug, composer, work, movement, section_label, instrument, difficulty, typical_prep_weeks, reference_tempo_range, aliases)
values ('wagner-tannhaeuser-overture', 'Wagner', 'Tannhäuser', 'Overture', 'Arpeggio passages', 'harp', 4, 4, null, array['Tannhauser', 'Tannhauser overture'])
on conflict (slug) do update set
  composer = excluded.composer, work = excluded.work, movement = excluded.movement,
  section_label = excluded.section_label, difficulty = excluded.difficulty,
  typical_prep_weeks = excluded.typical_prep_weeks,
  reference_tempo_range = excluded.reference_tempo_range, aliases = excluded.aliases;

insert into excerpts (slug, composer, work, movement, section_label, instrument, difficulty, typical_prep_weeks, reference_tempo_range, aliases)
values ('wagner-walkuere-magic-fire', 'Wagner', 'Die Walküre', 'Act III', 'Magic Fire Music', 'harp', 4, 4, null, array['Magic Fire Music', 'Walkure', 'Die Walkure'])
on conflict (slug) do update set
  composer = excluded.composer, work = excluded.work, movement = excluded.movement,
  section_label = excluded.section_label, difficulty = excluded.difficulty,
  typical_prep_weeks = excluded.typical_prep_weeks,
  reference_tempo_range = excluded.reference_tempo_range, aliases = excluded.aliases;

insert into excerpts (slug, composer, work, movement, section_label, instrument, difficulty, typical_prep_weeks, reference_tempo_range, aliases)
values ('franck-symphony-dminor-mvt2', 'Franck', 'Symphony in D minor', 'II. Allegretto', 'Opening pizzicato/harp texture', 'harp', 3, 3, null, array['Franck symphony', 'Franck D minor'])
on conflict (slug) do update set
  composer = excluded.composer, work = excluded.work, movement = excluded.movement,
  section_label = excluded.section_label, difficulty = excluded.difficulty,
  typical_prep_weeks = excluded.typical_prep_weeks,
  reference_tempo_range = excluded.reference_tempo_range, aliases = excluded.aliases;

insert into excerpts (slug, composer, work, movement, section_label, instrument, difficulty, typical_prep_weeks, reference_tempo_range, aliases)
values ('bizet-carmen-entracte3', 'Bizet', 'Carmen', 'Entr’acte to Act III', 'Flute/harp duet', 'harp', 3, 3, null, array['Carmen entracte', 'Carmen Act 3'])
on conflict (slug) do update set
  composer = excluded.composer, work = excluded.work, movement = excluded.movement,
  section_label = excluded.section_label, difficulty = excluded.difficulty,
  typical_prep_weeks = excluded.typical_prep_weeks,
  reference_tempo_range = excluded.reference_tempo_range, aliases = excluded.aliases;

insert into excerpts (slug, composer, work, movement, section_label, instrument, difficulty, typical_prep_weeks, reference_tempo_range, aliases)
values ('berlioz-romeo-et-juliette-fete', 'Berlioz', 'Roméo et Juliette', 'Fête chez Capulet', null, 'harp', 4, 4, null, array['Romeo et Juliette', 'Berlioz Romeo'])
on conflict (slug) do update set
  composer = excluded.composer, work = excluded.work, movement = excluded.movement,
  section_label = excluded.section_label, difficulty = excluded.difficulty,
  typical_prep_weeks = excluded.typical_prep_weeks,
  reference_tempo_range = excluded.reference_tempo_range, aliases = excluded.aliases;

insert into excerpts (slug, composer, work, movement, section_label, instrument, difficulty, typical_prep_weeks, reference_tempo_range, aliases)
values ('berlioz-harold-en-italie-mvt1', 'Berlioz', 'Harold en Italie', 'I.', 'Harp arpeggios with solo viola', 'harp', 3, 3, null, array['Harold in Italy'])
on conflict (slug) do update set
  composer = excluded.composer, work = excluded.work, movement = excluded.movement,
  section_label = excluded.section_label, difficulty = excluded.difficulty,
  typical_prep_weeks = excluded.typical_prep_weeks,
  reference_tempo_range = excluded.reference_tempo_range, aliases = excluded.aliases;

insert into excerpts (slug, composer, work, movement, section_label, instrument, difficulty, typical_prep_weeks, reference_tempo_range, aliases)
values ('rimsky-korsakov-scheherazade-cadenzas', 'Rimsky-Korsakov', 'Scheherazade', null, 'Cadenzas accompanying solo violin', 'harp', 3, 3, null, array['Scheherazade'])
on conflict (slug) do update set
  composer = excluded.composer, work = excluded.work, movement = excluded.movement,
  section_label = excluded.section_label, difficulty = excluded.difficulty,
  typical_prep_weeks = excluded.typical_prep_weeks,
  reference_tempo_range = excluded.reference_tempo_range, aliases = excluded.aliases;

insert into excerpts (slug, composer, work, movement, section_label, instrument, difficulty, typical_prep_weeks, reference_tempo_range, aliases)
values ('liszt-les-preludes', 'Liszt', 'Les préludes', null, 'Harp arpeggio passages', 'harp', 3, 3, null, array['Les preludes'])
on conflict (slug) do update set
  composer = excluded.composer, work = excluded.work, movement = excluded.movement,
  section_label = excluded.section_label, difficulty = excluded.difficulty,
  typical_prep_weeks = excluded.typical_prep_weeks,
  reference_tempo_range = excluded.reference_tempo_range, aliases = excluded.aliases;

insert into excerpts (slug, composer, work, movement, section_label, instrument, difficulty, typical_prep_weeks, reference_tempo_range, aliases)
values ('holst-planets-venus', 'Holst', 'The Planets', 'II. Venus / IV. Jupiter', 'Harp 1 exposed passages', 'harp', 3, 3, null, array['The Planets', 'Venus', 'Holst Planets'])
on conflict (slug) do update set
  composer = excluded.composer, work = excluded.work, movement = excluded.movement,
  section_label = excluded.section_label, difficulty = excluded.difficulty,
  typical_prep_weeks = excluded.typical_prep_weeks,
  reference_tempo_range = excluded.reference_tempo_range, aliases = excluded.aliases;

insert into excerpts (slug, composer, work, movement, section_label, instrument, difficulty, typical_prep_weeks, reference_tempo_range, aliases)
values ('stravinsky-firebird-berceuse', 'Stravinsky', 'The Firebird (1919 Suite)', 'Berceuse & Variation de l’oiseau de feu', null, 'harp', 4, 4, null, array['Firebird', 'Firebird berceuse'])
on conflict (slug) do update set
  composer = excluded.composer, work = excluded.work, movement = excluded.movement,
  section_label = excluded.section_label, difficulty = excluded.difficulty,
  typical_prep_weeks = excluded.typical_prep_weeks,
  reference_tempo_range = excluded.reference_tempo_range, aliases = excluded.aliases;

insert into excerpts (slug, composer, work, movement, section_label, instrument, difficulty, typical_prep_weeks, reference_tempo_range, aliases)
values ('prokofiev-romeo-juliet', 'Prokofiev', 'Romeo and Juliet', null, 'Suite excerpts (Juliet as a Young Girl, balcony scene)', 'harp', 3, 3, null, array['Prokofiev Romeo'])
on conflict (slug) do update set
  composer = excluded.composer, work = excluded.work, movement = excluded.movement,
  section_label = excluded.section_label, difficulty = excluded.difficulty,
  typical_prep_weeks = excluded.typical_prep_weeks,
  reference_tempo_range = excluded.reference_tempo_range, aliases = excluded.aliases;

insert into excerpts (slug, composer, work, movement, section_label, instrument, difficulty, typical_prep_weeks, reference_tempo_range, aliases)
values ('prokofiev-lieutenant-kije-romance', 'Prokofiev', 'Lieutenant Kijé', 'II. Romance', null, 'harp', 2, 2, null, array['Lieutenant Kije', 'Kije Romance'])
on conflict (slug) do update set
  composer = excluded.composer, work = excluded.work, movement = excluded.movement,
  section_label = excluded.section_label, difficulty = excluded.difficulty,
  typical_prep_weeks = excluded.typical_prep_weeks,
  reference_tempo_range = excluded.reference_tempo_range, aliases = excluded.aliases;

insert into excerpts (slug, composer, work, movement, section_label, instrument, difficulty, typical_prep_weeks, reference_tempo_range, aliases)
values ('shostakovich-symphony5', 'Shostakovich', 'Symphony No. 5', null, 'Exposed passages (mvts I & IV)', 'harp', 3, 3, null, array['Shostakovich 5', 'Shosty 5'])
on conflict (slug) do update set
  composer = excluded.composer, work = excluded.work, movement = excluded.movement,
  section_label = excluded.section_label, difficulty = excluded.difficulty,
  typical_prep_weeks = excluded.typical_prep_weeks,
  reference_tempo_range = excluded.reference_tempo_range, aliases = excluded.aliases;

insert into excerpts (slug, composer, work, movement, section_label, instrument, difficulty, typical_prep_weeks, reference_tempo_range, aliases)
values ('respighi-pines-of-rome', 'Respighi', 'Pines of Rome', null, 'Harp 1 exposed passages', 'harp', 3, 3, null, array['Pines of Rome', 'Pini di Roma'])
on conflict (slug) do update set
  composer = excluded.composer, work = excluded.work, movement = excluded.movement,
  section_label = excluded.section_label, difficulty = excluded.difficulty,
  typical_prep_weeks = excluded.typical_prep_weeks,
  reference_tempo_range = excluded.reference_tempo_range, aliases = excluded.aliases;

insert into excerpts (slug, composer, work, movement, section_label, instrument, difficulty, typical_prep_weeks, reference_tempo_range, aliases)
values ('respighi-fountains-of-rome', 'Respighi', 'Fountains of Rome', null, 'Harp 1 exposed passages', 'harp', 3, 3, null, array['Fountains of Rome', 'Fontane di Roma'])
on conflict (slug) do update set
  composer = excluded.composer, work = excluded.work, movement = excluded.movement,
  section_label = excluded.section_label, difficulty = excluded.difficulty,
  typical_prep_weeks = excluded.typical_prep_weeks,
  reference_tempo_range = excluded.reference_tempo_range, aliases = excluded.aliases;

insert into excerpts (slug, composer, work, movement, section_label, instrument, difficulty, typical_prep_weeks, reference_tempo_range, aliases)
values ('falla-three-cornered-hat', 'Falla', 'El sombrero de tres picos', null, 'Suite excerpts', 'harp', 4, 4, null, array['Three-Cornered Hat', 'El sombrero'])
on conflict (slug) do update set
  composer = excluded.composer, work = excluded.work, movement = excluded.movement,
  section_label = excluded.section_label, difficulty = excluded.difficulty,
  typical_prep_weeks = excluded.typical_prep_weeks,
  reference_tempo_range = excluded.reference_tempo_range, aliases = excluded.aliases;

insert into excerpts (slug, composer, work, movement, section_label, instrument, difficulty, typical_prep_weeks, reference_tempo_range, aliases)
values ('ginastera-variaciones-concertantes-harp-variation', 'Ginastera', 'Variaciones concertantes', null, 'Opening cello/harp duo', 'harp', 4, 5, null, array['Variaciones concertantes'])
on conflict (slug) do update set
  composer = excluded.composer, work = excluded.work, movement = excluded.movement,
  section_label = excluded.section_label, difficulty = excluded.difficulty,
  typical_prep_weeks = excluded.typical_prep_weeks,
  reference_tempo_range = excluded.reference_tempo_range, aliases = excluded.aliases;

insert into excerpts (slug, composer, work, movement, section_label, instrument, difficulty, typical_prep_weeks, reference_tempo_range, aliases)
values ('copland-appalachian-spring', 'Copland', 'Appalachian Spring', null, 'Exposed harp passages', 'harp', 3, 3, null, array['Appalachian Spring'])
on conflict (slug) do update set
  composer = excluded.composer, work = excluded.work, movement = excluded.movement,
  section_label = excluded.section_label, difficulty = excluded.difficulty,
  typical_prep_weeks = excluded.typical_prep_weeks,
  reference_tempo_range = excluded.reference_tempo_range, aliases = excluded.aliases;

insert into excerpts (slug, composer, work, movement, section_label, instrument, difficulty, typical_prep_weeks, reference_tempo_range, aliases)
values ('britten-peter-grimes-moonlight', 'Britten', 'Peter Grimes: Four Sea Interludes', 'III. Moonlight', null, 'harp', 3, 3, null, array['Sea Interludes', 'Moonlight interlude'])
on conflict (slug) do update set
  composer = excluded.composer, work = excluded.work, movement = excluded.movement,
  section_label = excluded.section_label, difficulty = excluded.difficulty,
  typical_prep_weeks = excluded.typical_prep_weeks,
  reference_tempo_range = excluded.reference_tempo_range, aliases = excluded.aliases;

insert into excerpts (slug, composer, work, movement, section_label, instrument, difficulty, typical_prep_weeks, reference_tempo_range, aliases)
values ('bartok-concerto-for-orchestra', 'Bartók', 'Concerto for Orchestra', null, 'Harp 1 exposed passages', 'harp', 3, 3, null, array['Bartok Concerto for Orchestra', 'CfO'])
on conflict (slug) do update set
  composer = excluded.composer, work = excluded.work, movement = excluded.movement,
  section_label = excluded.section_label, difficulty = excluded.difficulty,
  typical_prep_weeks = excluded.typical_prep_weeks,
  reference_tempo_range = excluded.reference_tempo_range, aliases = excluded.aliases;

insert into excerpts (slug, composer, work, movement, section_label, instrument, difficulty, typical_prep_weeks, reference_tempo_range, aliases)
values ('verdi-forza-overture', 'Verdi', 'La forza del destino', 'Overture', 'Harp arpeggios under melody', 'harp', 3, 3, null, array['Forza', 'La forza del destino'])
on conflict (slug) do update set
  composer = excluded.composer, work = excluded.work, movement = excluded.movement,
  section_label = excluded.section_label, difficulty = excluded.difficulty,
  typical_prep_weeks = excluded.typical_prep_weeks,
  reference_tempo_range = excluded.reference_tempo_range, aliases = excluded.aliases;

insert into excerpts (slug, composer, work, movement, section_label, instrument, difficulty, typical_prep_weeks, reference_tempo_range, aliases)
values ('puccini-tosca-act1', 'Puccini', 'Tosca', null, 'Act I harp passages', 'harp', 3, 3, null, array['Tosca'])
on conflict (slug) do update set
  composer = excluded.composer, work = excluded.work, movement = excluded.movement,
  section_label = excluded.section_label, difficulty = excluded.difficulty,
  typical_prep_weeks = excluded.typical_prep_weeks,
  reference_tempo_range = excluded.reference_tempo_range, aliases = excluded.aliases;

insert into excerpts (slug, composer, work, movement, section_label, instrument, difficulty, typical_prep_weeks, reference_tempo_range, aliases)
values ('dvorak-rusalka-song-to-the-moon', 'Dvořák', 'Rusalka', null, 'Song to the Moon accompaniment', 'harp', 2, 2, null, array['Rusalka', 'Song to the Moon'])
on conflict (slug) do update set
  composer = excluded.composer, work = excluded.work, movement = excluded.movement,
  section_label = excluded.section_label, difficulty = excluded.difficulty,
  typical_prep_weeks = excluded.typical_prep_weeks,
  reference_tempo_range = excluded.reference_tempo_range, aliases = excluded.aliases;

insert into excerpts (slug, composer, work, movement, section_label, instrument, difficulty, typical_prep_weeks, reference_tempo_range, aliases)
values ('gershwin-american-in-paris', 'Gershwin', 'An American in Paris', null, 'Exposed harp passages', 'harp', 3, 3, null, array['American in Paris'])
on conflict (slug) do update set
  composer = excluded.composer, work = excluded.work, movement = excluded.movement,
  section_label = excluded.section_label, difficulty = excluded.difficulty,
  typical_prep_weeks = excluded.typical_prep_weeks,
  reference_tempo_range = excluded.reference_tempo_range, aliases = excluded.aliases;

insert into excerpts (slug, composer, work, movement, section_label, instrument, difficulty, typical_prep_weeks, reference_tempo_range, aliases)
values ('barber-medea-dance-of-vengeance', 'Barber', 'Medea''s Meditation and Dance of Vengeance', null, null, 'harp', 4, 4, null, array['Medea'])
on conflict (slug) do update set
  composer = excluded.composer, work = excluded.work, movement = excluded.movement,
  section_label = excluded.section_label, difficulty = excluded.difficulty,
  typical_prep_weeks = excluded.typical_prep_weeks,
  reference_tempo_range = excluded.reference_tempo_range, aliases = excluded.aliases;

insert into excerpts (slug, composer, work, movement, section_label, instrument, difficulty, typical_prep_weeks, reference_tempo_range, aliases)
values ('brahms-ein-deutsches-requiem', 'Brahms', 'Ein deutsches Requiem', null, 'Harp part (mvts I & VII)', 'harp', 2, 2, null, array['German Requiem', 'Brahms Requiem'])
on conflict (slug) do update set
  composer = excluded.composer, work = excluded.work, movement = excluded.movement,
  section_label = excluded.section_label, difficulty = excluded.difficulty,
  typical_prep_weeks = excluded.typical_prep_weeks,
  reference_tempo_range = excluded.reference_tempo_range, aliases = excluded.aliases;

insert into excerpts (slug, composer, work, movement, section_label, instrument, difficulty, typical_prep_weeks, reference_tempo_range, aliases)
values ('saint-saens-carnival-aquarium', 'Saint-Saëns', 'Le carnaval des animaux', 'VII. Aquarium', null, 'harp', 2, 2, null, array['Carnival of the Animals', 'Aquarium'])
on conflict (slug) do update set
  composer = excluded.composer, work = excluded.work, movement = excluded.movement,
  section_label = excluded.section_label, difficulty = excluded.difficulty,
  typical_prep_weeks = excluded.typical_prep_weeks,
  reference_tempo_range = excluded.reference_tempo_range, aliases = excluded.aliases;

insert into excerpts (slug, composer, work, movement, section_label, instrument, difficulty, typical_prep_weeks, reference_tempo_range, aliases)
values ('faure-pavane', 'Fauré', 'Pavane, Op. 50', null, 'Harp part', 'harp', 2, 2, null, array['Faure Pavane'])
on conflict (slug) do update set
  composer = excluded.composer, work = excluded.work, movement = excluded.movement,
  section_label = excluded.section_label, difficulty = excluded.difficulty,
  typical_prep_weeks = excluded.typical_prep_weeks,
  reference_tempo_range = excluded.reference_tempo_range, aliases = excluded.aliases;

insert into excerpts (slug, composer, work, movement, section_label, instrument, difficulty, typical_prep_weeks, reference_tempo_range, aliases)
values ('faure-impromptu-op86', 'Fauré', 'Impromptu, Op. 86', null, null, 'harp', 5, 10, null, array['Faure Impromptu'])
on conflict (slug) do update set
  composer = excluded.composer, work = excluded.work, movement = excluded.movement,
  section_label = excluded.section_label, difficulty = excluded.difficulty,
  typical_prep_weeks = excluded.typical_prep_weeks,
  reference_tempo_range = excluded.reference_tempo_range, aliases = excluded.aliases;

insert into excerpts (slug, composer, work, movement, section_label, instrument, difficulty, typical_prep_weeks, reference_tempo_range, aliases)
values ('salzedo-variations-theme-ancient-style', 'Salzedo', 'Variations sur un thème dans le style ancien', null, null, 'harp', 4, 8, null, array['Salzedo Variations'])
on conflict (slug) do update set
  composer = excluded.composer, work = excluded.work, movement = excluded.movement,
  section_label = excluded.section_label, difficulty = excluded.difficulty,
  typical_prep_weeks = excluded.typical_prep_weeks,
  reference_tempo_range = excluded.reference_tempo_range, aliases = excluded.aliases;

insert into excerpts (slug, composer, work, movement, section_label, instrument, difficulty, typical_prep_weeks, reference_tempo_range, aliases)
values ('hindemith-harp-sonata-mvt1', 'Hindemith', 'Sonata for Harp', 'I. Mäßig schnell', null, 'harp', 4, 8, null, array['Hindemith sonata'])
on conflict (slug) do update set
  composer = excluded.composer, work = excluded.work, movement = excluded.movement,
  section_label = excluded.section_label, difficulty = excluded.difficulty,
  typical_prep_weeks = excluded.typical_prep_weeks,
  reference_tempo_range = excluded.reference_tempo_range, aliases = excluded.aliases;

insert into excerpts (slug, composer, work, movement, section_label, instrument, difficulty, typical_prep_weeks, reference_tempo_range, aliases)
values ('britten-suite-for-harp-op83', 'Britten', 'Suite for Harp, Op. 83', null, 'Overture', 'harp', 4, 8, null, array['Britten suite'])
on conflict (slug) do update set
  composer = excluded.composer, work = excluded.work, movement = excluded.movement,
  section_label = excluded.section_label, difficulty = excluded.difficulty,
  typical_prep_weeks = excluded.typical_prep_weeks,
  reference_tempo_range = excluded.reference_tempo_range, aliases = excluded.aliases;

insert into excerpts (slug, composer, work, movement, section_label, instrument, difficulty, typical_prep_weeks, reference_tempo_range, aliases)
values ('debussy-en-bateau', 'Debussy', 'Petite Suite', 'I. En bateau', 'Harp arrangement', 'harp', 2, 3, null, array['En bateau'])
on conflict (slug) do update set
  composer = excluded.composer, work = excluded.work, movement = excluded.movement,
  section_label = excluded.section_label, difficulty = excluded.difficulty,
  typical_prep_weeks = excluded.typical_prep_weeks,
  reference_tempo_range = excluded.reference_tempo_range, aliases = excluded.aliases;

delete from excerpt_knowledge where excerpt_id = (select id from excerpts where slug = 'berlioz-symphonie-fantastique-un-bal-harp1');
insert into excerpt_knowledge (excerpt_id, technical_traps, practice_strategies, committee_expectations, common_failure_modes, source_attribution)
select id, array['The opening cadenza sits against a fermata, not a beat — committees know the conductor will not wait; keep internal pulse so the final arpeggio lands with the downbeat, not after it.', 'Descending scale in the second cadenza requires a full pedal reset (to A-flat major territory) while both hands are occupied; plan the reset two bars early and mark exactly where each foot moves.', 'The waltz accompaniment reads easy but the left-hand leaps sit exactly where buzzing happens if you over-cover; practice placing without damping the ringing chord above.'], array['Practice both cadenzas with a drone on the resolution pitch so the arrival tempo and tuning target are fixed in the ear before adding rubato.', 'Tempo-ladder the scale runs in 4-note groupings, displacing the grouping accent every other day to break mechanical patterning.', 'Run the movement entrance-to-entrance with a recording of the full orchestra at least twice a week — the traps are the handoffs, not the notes.'], 'Committees listen for a real waltz — one, not three — and for cadenzas that sound free but land exactly in tempo. Behind a screen, uneven scale rhythm and pedal noise are the two instant tells.', array['Rushing the final third of each cadenza under adrenaline.', 'Audible pedal thump during the reset before the second cadenza.', 'Playing the waltz accompaniment too vertically — no lilt.'], 'Curated by resident harp expert; standard US audition practice.'
from excerpts where slug = 'berlioz-symphonie-fantastique-un-bal-harp1';

delete from excerpt_knowledge where excerpt_id = (select id from excerpts where slug = 'tchaikovsky-nutcracker-waltz-of-the-flowers-cadenza');
insert into excerpt_knowledge (excerpt_id, technical_traps, practice_strategies, committee_expectations, common_failure_modes, source_attribution)
select id, array['The cadenza is one long crescendo architecture — pacing it as four separate gestures is the most common structural mistake.', 'Rolled chords at the climax need the top voice to carry; over-rolling swallows the melody note behind a screen.', 'The final descending arpeggios invite a hand-position collapse at speed; fingers 4-3-2-1 placement must stay identical from slow tempo to performance tempo.'], array['Map the dynamic architecture on paper first: one peak, everything else relative to it.', 'Practice the climax chords melodically — top line alone, then add the roll underneath at half volume.', 'Record at three tempos (slow, medium, target) weekly; compare evenness, not speed.'], 'This is the single most-heard harp excerpt; committees have an exact template in their ear. They want inevitability — a cadenza that breathes but never stalls — and a climax that blooms without banging.', array['Starting too loud, leaving nowhere to go.', 'Uneven arpeggio rhythm in the final descent.', 'Clipping the last harmonic-like resolution because of early damping.'], 'Curated by resident harp expert; standard US audition practice.'
from excerpts where slug = 'tchaikovsky-nutcracker-waltz-of-the-flowers-cadenza';

delete from excerpt_knowledge where excerpt_id = (select id from excerpts where slug = 'debussy-danses-sacree-et-profane');
insert into excerpt_knowledge (excerpt_id, technical_traps, practice_strategies, committee_expectations, common_failure_modes, source_attribution)
select id, array['Danse sacrée: the modal exposed opening has zero cover — intonation of the instrument itself (regulation, pedal seating) is audible; check pedal seating on every pedal before the run.', 'Danse profane: the 3/4 waltz cross-rhythms against the string ostinato drift early if you practice it only solo; the trap is ensemble, not fingers.', 'The transition between the two dances requires a discreet multi-pedal change during a held string chord — choreograph feet exactly.'], array['Practice with the string reduction (recording or piano) from week one; this piece fails in ensemble, not in the practice room.', 'Isolate every pedal change into a "feet-only" run: play nothing, execute all pedals in rhythm.', 'For the profane, metronome on beat 2 only — forces ownership of the waltz shape.'], 'Usually requested complete or as the sacrée alone. Committees listen for tone color contrast between the two dances and for rhythmic integrity in the profane. This is where they judge musicianship, not just accuracy.', array['Treating the sacrée as free when it is strict.', 'Profane accelerating through the central climb.', 'Muddy overlapping resonance from under-damping in the modal opening.'], 'Curated by resident harp expert; standard US audition practice.'
from excerpts where slug = 'debussy-danses-sacree-et-profane';

delete from excerpt_knowledge where excerpt_id = (select id from excerpts where slug = 'ravel-introduction-et-allegro');
insert into excerpt_knowledge (excerpt_id, technical_traps, practice_strategies, committee_expectations, common_failure_modes, source_attribution)
select id, array['The solo cadenza harmonics must project — harmonic placement drifting even a centimeter kills them at the back of a hall.', 'The Allegro’s perpetual texture hides the melody in the thumb; thumb voicing at speed is the core technical problem of the piece.', 'Glissando spans require precise pedal spellings; one wrong pedal turns a chord gliss into noise.'], array['Write every glissando’s pedal spelling into the part and drill spellings away from the instrument.', 'Thumb-melody-only practice of the Allegro texture: play just the thumbs, sing the rest.', 'Cadenza harmonics daily, eyes closed, to fix placement kinesthetically rather than visually.'], 'The de facto concerto of the instrument — when it appears on a list, it is the round-decider. Committees expect complete technical command plus real French color: clarity without dryness.', array['Dead or buzzing harmonics in the cadenza.', 'Melody drowned by accompaniment texture at tempo.', 'Tempo inflation through the final pages.'], 'Curated by resident harp expert; standard US audition practice.'
from excerpts where slug = 'ravel-introduction-et-allegro';

delete from excerpt_knowledge where excerpt_id = (select id from excerpts where slug = 'ravel-tzigane-cadenza');
insert into excerpt_knowledge (excerpt_id, technical_traps, practice_strategies, committee_expectations, common_failure_modes, source_attribution)
select id, array['The figuration imitates the violin’s opening cadenza — committees who know the piece expect the same rubato logic; learning it without studying the violin part misses the point.', 'Rapid near-glissando figuration is written out — the temptation to fake it as a true gliss is audible to any string player in the room.', 'Sustained trill-like tremolo between the hands must stay even while the dynamic swells.'], array['Learn the violin cadenza by ear first; your part is its echo.', 'Practice written-out runs as measured groups at half speed until the pattern is honest, then free it.', 'Isolate the tremolo with a decibel target: even at fortissimo, no rhythmic clumping.'], 'Appears on lists to test color and rubato control. The screen hides everything but timing — a metronomically stiff Tzigane reads as unmusical, a smeared one as unprepared.', array['Faking the written figuration as glissando.', 'Rubato that loses the underlying line.', 'Weak dynamic ceiling — the excerpt sounds small.'], 'Curated by resident harp expert; standard US audition practice.'
from excerpts where slug = 'ravel-tzigane-cadenza';

delete from excerpt_knowledge where excerpt_id = (select id from excerpts where slug = 'britten-young-persons-guide-variation');
insert into excerpt_knowledge (excerpt_id, technical_traps, practice_strategies, committee_expectations, common_failure_modes, source_attribution)
select id, array['The variation is a rhythm test disguised as a flourish: the dotted figures against the tutti must be exact or the whole variation sounds approximate.', 'Big chordal glissandi need pedal spellings set during the previous variation — there is no time once yours starts.', 'The final flourish tempts a ritard that is not written; conductors do not give one.'], array['Practice with the preceding percussion variation audible (recording) to nail the entrance.', 'Subdivide the dotted rhythms at the sixteenth level with metronome before allowing full tempo.', 'Drill the pedal presets as a standalone choreography, in rhythm, hands in lap.'], 'A rhythm-and-nerve excerpt: committees want brilliance that stays inside the grid. It is usually placed early in a round to test whether the candidate can be flashy and disciplined simultaneously.', array['Late entrance after the percussion variation.', 'Rhythmic approximation in dotted figures.', 'Unwritten ritard at the end.'], 'Curated by resident harp expert; standard US audition practice.'
from excerpts where slug = 'britten-young-persons-guide-variation';

delete from excerpt_knowledge where excerpt_id = (select id from excerpts where slug = 'donizetti-lucia-harp-solo');
insert into excerpt_knowledge (excerpt_id, technical_traps, practice_strategies, committee_expectations, common_failure_modes, source_attribution)
select id, array['Operatic solo with the orchestra tacet — every damping choice is exposed; the resonance plan matters as much as the notes.', 'Bel canto ornaments must sound vocal: turns and grace notes placed as a singer breathes, not as a drill.', 'The cadential runs need a real dynamic floor — pianissimo that still speaks in a 2,000-seat house.'], array['Study two or three soprano recordings of the following aria; steal their breathing points for your phrasing.', 'Mark a full damping map: what rings, what is stopped, where.', 'Practice projection at pianissimo: record from across the room and check audibility.'], 'Opera-house lists use this as the musicianship centerpiece. Committees want singing line, tasteful ornaments, and total control of resonance — technique in service of a voice.', array['Instrumental (square) ornament placement.', 'Wash of undamped resonance blurring harmonies.', 'Inaudible pianissimo runs.'], 'Curated by resident harp expert; standard US audition practice.'
from excerpts where slug = 'donizetti-lucia-harp-solo';

delete from excerpt_knowledge where excerpt_id = (select id from excerpts where slug = 'mahler-symphony5-adagietto');
insert into excerpt_knowledge (excerpt_id, technical_traps, practice_strategies, committee_expectations, common_failure_modes, source_attribution)
select id, array['You are the pulse of the whole movement — the strings float on your eighths; any unevenness telegraphs immediately.', 'The dynamic is a corridor between pp and mp for pages; producing a warm, non-percussive attack at that level is the actual skill being tested.', 'Long rests between entries: counting lapses here are legendary.'], array['Practice with a recording and conduct the string line while playing — internalize the movement as chamber music.', 'Tone work: single-note attacks at pp, aiming for bloom without pluck, ten minutes daily.', 'Sing the cello line during your rests in run-throughs.'], 'Committees use the Adagietto to hear tone and time. Nothing is hard on paper; everything is exposed in sound. Rushing the eighth-notes even slightly is the most common reason this excerpt eliminates candidates.', array['Creeping ahead of the (imagined) string line.', 'Percussive attack at low dynamics.', 'Losing count in tacet bars and re-entering early.'], 'Curated by resident harp expert; standard US audition practice.'
from excerpts where slug = 'mahler-symphony5-adagietto';

delete from excerpt_knowledge where excerpt_id = (select id from excerpts where slug = 'smetana-vysehrad-opening');
insert into excerpt_knowledge (excerpt_id, technical_traps, practice_strategies, committee_expectations, common_failure_modes, source_attribution)
select id, array['The opening is a duet for two harps in most editions — know which part the list asks for and whether they expect the composite.', 'Bardic arpeggio chords must sound improvisatory while being metrically exact underneath.', 'Wide rolled chords risk top-voice burial; the melody note is the last thing struck and must be the loudest.'], array['Practice chord rolls bottom-up with a crescendo into the top voice.', 'Alternate strict and free run-throughs to find the rubato that still scans.', 'If harp 2 exists in your edition, learn both parts — committees occasionally switch.'], 'An opening-of-the-round staple: it warms the room and shows tone immediately. Committees want nobility and space, not speed.', array['Rolling chords so slowly the harmony smears.', 'Burying the melodic top voice.', 'Over-rubato that loses the underlying march of the theme.'], 'Curated by resident harp expert; standard US audition practice.'
from excerpts where slug = 'smetana-vysehrad-opening';

delete from excerpt_knowledge where excerpt_id = (select id from excerpts where slug = 'rimsky-korsakov-capriccio-espagnol-cadenza');
insert into excerpt_knowledge (excerpt_id, technical_traps, practice_strategies, committee_expectations, common_failure_modes, source_attribution)
select id, array['The cadenza alternates rolled chords and single-line flourishes — the chords set the harmonic frame and must not rush even when the flourishes fly.', 'Repeated-note figures on gut strings choke if the replacing finger arrives late; drill finger substitution slowly.', 'The ending hands off directly to the ensemble — the last gesture must land in the conductor’s tempo, not yours.'], array['Separate the two textures: chords-only pass, flourishes-only pass, then interleave.', 'Practice the final two bars with a metronome set to the movement tempo that follows.', 'Record and check that the flourishes accelerate by design, not by accident.'], 'A flash excerpt — committees expect sparkle and confidence. It rewards decisiveness; a cautious Capriccio reads worse than a slightly imperfect bold one.', array['Choked repeated notes.', 'Chords rushing to match the flourishes.', 'Tentative dynamic range.'], 'Curated by resident harp expert; standard US audition practice.'
from excerpts where slug = 'rimsky-korsakov-capriccio-espagnol-cadenza';

delete from excerpt_knowledge where excerpt_id = (select id from excerpts where slug = 'tchaikovsky-swan-lake-act2-cadenza');
insert into excerpt_knowledge (excerpt_id, technical_traps, practice_strategies, committee_expectations, common_failure_modes, source_attribution)
select id, array['Ballet cadenza logic: the conductor will re-enter on the harp’s cue, so the final approach must be shaped as an upbeat, readable by a person you cannot see.', 'The arpeggio sweeps cover the whole range — shoulder tension at the top of the instrument narrows tone exactly where it is most exposed.', 'Grace-note figures before the beat versus on the beat: pick the convention your target orchestra uses (listen to their recording).'], array['End every practice run by conducting yourself into the following string entry.', 'Range-sweep warmups before this excerpt: two octaves, four octaves, full compass, watching tension.', 'A/B your grace-note placement against the target orchestra’s recording.'], 'Committees from ballet-heavy orchestras treat this as a first-round filter. They listen for a cadenza that breathes like accompaniment to dance — supple but never structurally loose.', array['Unreadable final ritenuto (no upbeat shape).', 'Thin tone at the top of sweeps.', 'Mechanical grace notes.'], 'Curated by resident harp expert; standard US audition practice.'
from excerpts where slug = 'tchaikovsky-swan-lake-act2-cadenza';

delete from excerpt_knowledge where excerpt_id = (select id from excerpts where slug = 'ravel-daphnis-suite2-lever-du-jour');
insert into excerpt_knowledge (excerpt_id, technical_traps, practice_strategies, committee_expectations, common_failure_modes, source_attribution)
select id, array['The running 32nd-note figuration is shared and layered with flutes/clarinets — your part is a color inside a machine; dynamic discipline is the trap.', 'Hand-crossing patterns lock up at tempo if fingered for comfort at slow tempo; finalize fingerings at 80% speed.', 'Page-long perpetual motion invites forearm tension; build endurance deliberately.'], array['Interval training: 90 seconds on, 30 off, repeated — builds the endurance the passage actually needs.', 'Practice against the woodwind recording at half volume to place yourself inside the texture.', 'Freeze-frame drill: stop on random beats and check both hand shapes.'], 'Committees check evenness and stamina — the excerpt fails by degradation, with bar 1 and bar 40 sounding like different players. Consistency beats brilliance here.', array['Texture degrading over the duration.', 'Dynamic bulging that breaks the orchestral blend.', 'Tension-induced tempo sag near the end.'], 'Curated by resident harp expert; standard US audition practice.'
from excerpts where slug = 'ravel-daphnis-suite2-lever-du-jour';

delete from excerpt_knowledge where excerpt_id = (select id from excerpts where slug = 'strauss-ein-heldenleben');
insert into excerpt_knowledge (excerpt_id, technical_traps, practice_strategies, committee_expectations, common_failure_modes, source_attribution)
select id, array['The love-scene arpeggios accompany a solo violin ad libitum — the excerpt tests following, so practicing it rigidly solo builds the wrong skill.', 'Low-register melodic fragments need cello-like tone, a different attack than the arpeggio texture around them.', 'Long span with many small entries: the counting/entrance map is half the preparation.'], array['Practice with two different recordings that take different liberties — trains real-time flexibility.', 'Isolate low-register fragments for tone: aim for bow-like swell.', 'Write and memorize an entrance map (what cues each entry) as a standalone artifact.'], 'A second-round staple for major orchestras. Committees — often including the concertmaster — listen for accompanying instincts: does the harp breathe with the violin line it cannot hear in the room?', array['Metronomic arpeggios that ignore the implied rubato.', 'Identical attack across contrasting textures.', 'Missed entrances in the long span.'], 'Curated by resident harp expert; standard US audition practice.'
from excerpts where slug = 'strauss-ein-heldenleben';

delete from excerpt_knowledge where excerpt_id = (select id from excerpts where slug = 'stravinsky-firebird-berceuse');
insert into excerpt_knowledge (excerpt_id, technical_traps, practice_strategies, committee_expectations, common_failure_modes, source_attribution)
select id, array['The Berceuse ostinato must be hypnotic — micro-accents from fingering pattern changes break the spell.', 'The Variation’s fast figuration includes awkward enharmonic pedal solutions; the standard spellings are not the printed ones — research performance practice.', 'Sudden dynamic terracing (Stravinsky’s blocks) with no romantic tapering.'], array['Loop the ostinato for two minutes at a time listening only for accent leaks.', 'Annotate enharmonic pedal solutions and drill them as spellings before playing.', 'Practice dynamic terracing with a hard switch — no crescendo — between blocks.'], 'Committees listen for style: Stravinsky played like Ravel is a stylistic red flag. Clean blocks, ostinato calm, and rhythmic exactness read as orchestral maturity.', array['Accent leaks in the ostinato.', 'Romantic phrasing applied to terraced dynamics.', 'Pedal noise in the Variation’s enharmonic passages.'], 'Curated by resident harp expert; standard US audition practice.'
from excerpts where slug = 'stravinsky-firebird-berceuse';

delete from excerpt_knowledge where excerpt_id = (select id from excerpts where slug = 'mozart-concerto-flute-harp-k299-mvt1');
insert into excerpt_knowledge (excerpt_id, technical_traps, practice_strategies, committee_expectations, common_failure_modes, source_attribution)
select id, array['Classical-era clarity: every note is exposed and the texture forgives nothing — scale evenness is the entire game.', 'The harp writing is pianistic; literal pedal-harp fingerings from the urtext often need redistribution between hands.', 'Cadenza choice matters: committees have heard every standard cadenza — a sloppy famous cadenza is worse than a clean simple one.'], array['Scale and arpeggio fundamentals in C and F major daily during prep — the concerto is those scales in costume.', 'Redistribute and mark hand divisions early; never renegotiate them mid-prep.', 'Choose the cadenza by week two and commit.'], 'The standard first-round solo. Committees want Mozart that dances — tempo integrity, ornament clarity, and Alberti-figure evenness. It reveals fundamentals more nakedly than any excerpt.', array['Uneven scale runs.', 'Ornaments crushing the beat.', 'Cadenza over-reach.'], 'Curated by resident harp expert; standard US audition practice.'
from excerpts where slug = 'mozart-concerto-flute-harp-k299-mvt1';
