/**
 * The live plan (spec §5): today's session checklist, generated by the
 * deterministic scheduler and written by the model. Missed days are absorbed,
 * never scored (§8).
 */

import { useFocusEffect, useRouter } from 'expo-router';
import React, { useCallback, useState } from 'react';
import { Alert, Text, View } from 'react-native';

import {
  Button,
  Card,
  Chip,
  Dim,
  EmptyState,
  Heading,
  Row,
  Screen,
  Title,
} from '../../src/components/ui';
import { excerptDisplayName, type ExcerptRow, type PlannedSessionRow, type PracticePlanRow } from '../../src/lib/db';
import { useAsync, useSession } from '../../src/lib/hooks';
import { buildMinimumViableSession, generateAndStorePlan, buildPlanInputs, loadPlanContext } from '../../src/lib/planPipeline';
import { supabase } from '../../src/lib/supabase';
import { colors, phaseMeta, spacing, type } from '../../src/theme';

function todayISO(): string {
  return new Date().toISOString().slice(0, 10);
}

export default function Plan() {
  const { session } = useSession();
  const router = useRouter();
  const userId = session?.user.id;
  const [generating, setGenerating] = useState(false);

  const { data, reload } = useAsync(async () => {
    if (!userId) return null;
    const [plan, excerpts] = await Promise.all([
      supabase
        .from('practice_plans')
        .select('*')
        .eq('user_id', userId)
        .eq('status', 'active')
        .maybeSingle(),
      supabase.from('excerpts').select('*'),
    ]);
    let sessions: PlannedSessionRow[] = [];
    if (plan.data) {
      const res = await supabase
        .from('planned_sessions')
        .select('*')
        .eq('plan_id', plan.data.id)
        .gte('date', todayISO())
        .order('date')
        .limit(7);
      sessions = (res.data ?? []) as PlannedSessionRow[];
    }
    return {
      plan: plan.data as PracticePlanRow | null,
      sessions,
      excerpts: (excerpts.data ?? []) as ExcerptRow[],
    };
  }, [userId]);

  useFocusEffect(useCallback(() => reload(), [reload]));

  const excerptById = new Map((data?.excerpts ?? []).map((e) => [e.id, e]));
  const nameOf = (id?: string) => {
    if (!id) return '';
    const e = excerptById.get(id);
    return e ? excerptDisplayName(e) : id;
  };

  async function generate() {
    if (!userId) return;
    setGenerating(true);
    try {
      const ctx = await loadPlanContext(userId);
      const inputs = buildPlanInputs(ctx, todayISO());
      if ('missing' in inputs) {
        if (inputs.missing.includes('profile')) {
          router.push('/profile-setup');
        } else {
          Alert.alert('Almost there', inputs.missing);
        }
        return;
      }
      await generateAndStorePlan(userId, todayISO());
      reload();
    } catch (e) {
      Alert.alert('Plan generation failed', String((e as Error).message ?? e));
    } finally {
      setGenerating(false);
    }
  }

  async function logSession(s: PlannedSessionRow, status: 'completed' | 'partial' | 'skipped') {
    await supabase.from('planned_sessions').update({ status }).eq('id', s.id);
    reload();
  }

  const today = data?.sessions.find((s) => s.date === todayISO());
  const upcoming = (data?.sessions ?? []).filter((s) => s.date !== todayISO());

  return (
    <Screen>
      <Title>Plan</Title>

      {!data?.plan ? (
        <>
          <EmptyState
            title="No plan yet"
            body="Once your auditions and rep are in, the planner periodizes everything backwards from each audition date."
          />
          <Button label={generating ? 'Working…' : 'Generate my plan'} onPress={generate} loading={generating} />
          <Button label="Practice profile" kind="secondary" onPress={() => router.push('/profile-setup')} />
        </>
      ) : (
        <>
          {today ? (
            <SessionCard session={today} nameOf={nameOf} onLog={logSession} isToday />
          ) : (
            <Card>
              <Heading>Rest day</Heading>
              <Dim>Nothing scheduled today. Rest is part of the plan, not a gap in it.</Dim>
            </Card>
          )}

          {today ? (
            <Button
              label="Bad day? Shrink to the minimum"
              kind="secondary"
              onPress={async () => {
                if (!userId || !today) return;
                const ctx = await loadPlanContext(userId);
                const inputs = buildPlanInputs(ctx, todayISO());
                if ('missing' in inputs) return;
                const mvs = buildMinimumViableSession(todayISO(), inputs);
                await supabase
                  .from('planned_sessions')
                  .update({ blocks: mvs.blocks, planned_minutes: mvs.plannedMinutes })
                  .eq('id', today.id);
                reload();
              }}
            />
          ) : null}

          {upcoming.length > 0 ? <Heading>This week</Heading> : null}
          {upcoming.map((s) => (
            <SessionCard key={s.id} session={s} nameOf={nameOf} onLog={logSession} />
          ))}

          <Button label={generating ? 'Working…' : 'Regenerate plan'} kind="ghost" onPress={generate} loading={generating} />
        </>
      )}
    </Screen>
  );
}

function SessionCard({
  session,
  nameOf,
  onLog,
  isToday = false,
}: {
  session: PlannedSessionRow;
  nameOf: (id?: string) => string;
  onLog: (s: PlannedSessionRow, status: 'completed' | 'partial' | 'skipped') => void;
  isToday?: boolean;
}) {
  const meta = phaseMeta[session.phase] ?? phaseMeta.consolidate;
  return (
    <Card style={isToday ? { borderColor: colors.accent } : undefined}>
      <Row style={{ justifyContent: 'space-between' }}>
        <Heading>{isToday ? 'Today' : session.date}</Heading>
        <Chip label={`${meta.label} · ${session.planned_minutes} min`} color={meta.color} />
      </Row>

      {session.blocks.map((b, i) => (
        <View key={i} style={{ marginBottom: spacing.sm }}>
          <Text style={type.body}>
            {b.kind === 'excerpt' ? nameOf(b.excerptId) : b.label}
            <Text style={type.small}>  {b.minutes} min</Text>
          </Text>
          {b.instructions ? <Dim>{b.instructions}</Dim> : null}
        </View>
      ))}

      {isToday && session.status === 'planned' ? (
        <Row>
          <Button label="Done" onPress={() => onLog(session, 'completed')} />
          <Button label="Partial" kind="secondary" onPress={() => onLog(session, 'partial')} />
          <Button label="Skip" kind="ghost" onPress={() => onLog(session, 'skipped')} />
        </Row>
      ) : null}
      {session.status !== 'planned' ? <Dim>Logged: {session.status}</Dim> : null}
    </Card>
  );
}
