/**
 * Generates supabase/seed.sql from src/data/seedExcerpts.ts so the canonical
 * library has exactly one source of truth.
 *
 * Run: npm run seed:sql
 */

import { mkdirSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';

import { SEED_EXCERPTS, SEED_KNOWLEDGE } from '../src/data/seedExcerpts.ts';

function q(value: string | undefined | null): string {
  if (value === undefined || value === null) return 'null';
  return `'${value.replace(/'/g, "''")}'`;
}

function arr(values: string[]): string {
  if (values.length === 0) return "'{}'::text[]";
  return `array[${values.map((v) => q(v)).join(', ')}]`;
}

const lines: string[] = [
  '-- Generated by scripts/generate-seed-sql.ts — do not edit by hand.',
  '-- Source of truth: src/data/seedExcerpts.ts',
  '',
];

for (const e of SEED_EXCERPTS) {
  const tempo = e.referenceTempoRange
    ? `'[${e.referenceTempoRange[0]},${e.referenceTempoRange[1]}]'::int4range`
    : 'null';
  lines.push(
    `insert into excerpts (slug, composer, work, movement, section_label, instrument, difficulty, typical_prep_weeks, reference_tempo_range, aliases)`,
    `values (${q(e.slug)}, ${q(e.composer)}, ${q(e.work)}, ${q(e.movement)}, ${q(e.sectionLabel)}, ${q(e.instrument)}, ${e.difficulty}, ${e.typicalPrepWeeks}, ${tempo}, ${arr(e.aliases)})`,
    `on conflict (slug) do update set`,
    `  composer = excluded.composer, work = excluded.work, movement = excluded.movement,`,
    `  section_label = excluded.section_label, difficulty = excluded.difficulty,`,
    `  typical_prep_weeks = excluded.typical_prep_weeks,`,
    `  reference_tempo_range = excluded.reference_tempo_range, aliases = excluded.aliases;`,
    '',
  );
}

for (const k of SEED_KNOWLEDGE) {
  lines.push(
    `delete from excerpt_knowledge where excerpt_id = (select id from excerpts where slug = ${q(k.slug)});`,
    `insert into excerpt_knowledge (excerpt_id, technical_traps, practice_strategies, committee_expectations, common_failure_modes, source_attribution)`,
    `select id, ${arr(k.technicalTraps)}, ${arr(k.practiceStrategies)}, ${q(k.committeeExpectations)}, ${arr(k.commonFailureModes)}, ${q(k.sourceAttribution)}`,
    `from excerpts where slug = ${q(k.slug)};`,
    '',
  );
}

const outPath = join(process.cwd(), 'supabase', 'seed.sql');
mkdirSync(dirname(outPath), { recursive: true });
writeFileSync(outPath, lines.join('\n'));
console.log(
  `Wrote ${outPath}: ${SEED_EXCERPTS.length} excerpts, ${SEED_KNOWLEDGE.length} knowledge entries.`,
);
